config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root to: "users#index"
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  get "home/", to: "pages#home"
  get "support/", to: "pages#support"

  resources :feedbacks, only: %i[index new edit create update destroy]

  resources :users, only: %i[index show] do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true, length: { maximum: 500 }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, length: { minimum: 2, maximum: 100 }
  validates :message, length: { minimum: 10, maximum: 500 }
end

app/models/post.rb
class Post < ApplicationRecord
  extend Enumerize
  STATUS = %w[draft public test].freeze

  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 400 }

  enumerize :status, in: STATUS, predicates: { prefix: true }
end

app/models/post_comments.rb
class PostComments < ApplicationRecord
  belongs_to :post
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize

  ROLES = %w[user admin].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :nullify
  has_many :feedbacks, dependent: :destroy

  enumerize :role, in: ROLES, predicates: { prefix: true }

  validates :name, :surname, presence: true, length: { minimum: 2, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :danger, :warning

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feedback, only: %i[edit update destroy]

  def index
    @feedbacks = current_user.feedbacks
  end

  def new
    @feedback = Feedback.new
  end

  def edit
  end

  def create
    @feedback = current_user.feedbacks.new(feedback_params)
    if @feedback.save
      FeedbackMailer.new_feedback(current_user, @feedback).deliver_later
      redirect_to feedbacks_path, notice: "Thank you for your feedback!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @feedback.update(feedback_params)
      redirect_to feedbacks_path, success: "Feedback was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @feedback.destroy
    redirect_to feedbacks_path, success: "Feedback was successfully destroyed."
  end

  private

  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  def feedback_params
    params.require(:feedback).permit(:title, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Post.where(status: "public")
  end

  def support
    @feedbacks = Feedback.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new update index]
  before_action -> { authorize! @post }, only: %i[edit update destroy]

  def index
    @posts = @user.posts
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = @user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(@user, @post), success: "post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      10.times { HandleTestPostJob.perform_later(@post, @user) } if post_params[:status] == "test"

      redirect_to user_post_path(@user, @post), success: "post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, success: "post was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :description, :status)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    def create
      super
    end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    def update
      super
    end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname])
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  before_action :set_decorated_user, only: %i[show]

  def index
    @decorated_users = User.excluding(current_user).decorate
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to root_path, success: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_decorated_user
    @decorated_user = set_user.decorate
  end

  def user_params
    params.require(:user).permit(:name, :surname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_posted(obj)
    if (obj.updated_at - obj.created_at) > 1
      "Edited #{time_ago_in_words(obj.updated_at)} ago"
    else
      "Posted #{time_ago_in_words(obj.created_at)} ago"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/contact_messages/user_index.html.erb
<h1>Contact Us</h1>
<%= link_to "write message", new_admin_contact_message_path, class: "btn btn-outline-primary btn-sm" %>

<div id="posts">
  <hr>
  <% @contact_messages.each do |contact_message| %>
    <h2><%= contact_message.title %></h2>
    <h5><%= contact_message.message %></h5>
    <hr>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %> container card mt-4 p-3">
  <div id="comment-body-<%= comment.id %>">
    <%= comment.body %>
  </div>
  <div id="edit-form-<%= comment.id %>" class="d-none">
    <%= render 'comments/form', user: @user, post: @post, comment: comment %>
  </div>
  <hr/>
  <span> <%= time_posted(comment) %>
    <% if current_user == comment.user %>
    <div class="btn-group float-end">
      <%= link_to "Edit", nil, remote: true, class: "btn btn-primary btn-sm",
      data: {
        controller: "comments"
      }%>
      <%= button_to "Delete", user_post_comment_path(user, post, comment), class: "btn btn-danger btn-sm", method: :delete %>
    </div>
  <% end %>
  </span>
  <%= comment.user.email %><br/>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [user, post, comment] do |form| %>
  <% if comment.errors.any? %>
    <div class="alert alert-warning">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-control">
    <%= form.rich_text_area :body %>
    <%= form.submit class: "btn btn-outline-primary btn-sm" %>
  </div>
<% end %>

app/views/feedbacks/_form.html.erb
<%= form_with model: feedback do |form| %>
  <% if feedback.errors.any? %>
    <div class="alert alert-warning">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% feedback.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label"  %><br />
    <%= form.text_field :title, autofocus: true, autocomplete: "title", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :message, class: "form-label"  %><br />
    <%= form.text_area :message, class:"form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-primary btn-sm" %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Message</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Back", :back %>
</div>

app/views/feedbacks/index.html.erb
<h1>Contact Us</h1>
<%= link_to "write message", new_feedback_path, class: "btn btn-outline-primary btn-sm" %>

<div id="posts">
  <hr>
  <% @feedbacks.each do |feedback| %>
    <h2><%= feedback.title %></h2>
    <p class="fs-5"><%= feedback.message %></p>
    <%= link_to "Edit", edit_feedback_path(feedback), class: "btn btn-outline-secondary btn-sm" %>
    <%= button_to "Destroy", feedback_path(feedback), method: :delete, class: "btn btn-outline-danger btn-sm" %>
    <hr>
  <% end %>
</div>

app/views/feedbacks/new.html.erb
<h1>Create Message</h1>

<%= render "form", feedback: @feedback %>

<br>

<div>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary btn-sm" %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/main_page/index.erb
<h1>All Posts</h1>
<div id="posts">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= link_to post.title, user_post_path(post.user_id, post) %></td>
        <td><%= post.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/main_page/index.html.erb
<h1>All Posts</h1>
<div id="posts">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= link_to post.title, user_post_path(post.user_id, post) %></td>
        <td><%= post.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/posts/_comment.erb
<%= comment.text %>
<br>

app/views/posts/_form.html.erb
<%= form_with model: [user, post] do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-warning">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "form-label" %><br />
    <%= form.text_field :title, autofocus: true, autocomplete: "title", class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :description, class: "form-label" %><br />
    <%= form.text_area :description, class:"form-control"  %>
  </div>

  <div class="field">
    <%= form.label :status, class: "form-label" %><br />
    <%= form.select :status, Post.status.values %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-primary btn-sm" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post, user: @user %>

<br>

<div>
  <%= link_to "Back to posts", user_posts_path(@user) %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= link_to "Create Post", new_user_post_path(current_user), class: "btn btn-outline-primary btn-sm" %>


<div id="posts">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= link_to post.title, user_post_path(post.user_id, post) %></td>
        <td><%= post.description %></td>
        <td><%= post.status %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", user: @user, post: @post %>

<br>

<div>
  <%= link_to "Back", :back, class: "btn btn-outline-secondary btn-sm"%>
</div>

app/views/posts/show.html.erb
<div class="card weight">
  <div class="card-body">
    <h5 class="card-title">Title</h5>
    <p class="card-text"><%= @post.title %></p>

    <h5 class="card-title">Description</h5>
    <p class="card-text"><%= @post.description %></p>

    <h5 class="card-title">Status</h5>
    <p class="card-text"><%= @post.status %></p>

    <div>
      <% if current_user != @post.user %>
        <%= link_to "Home", home_path, class: "btn btn-outline-primary btn-sm" %>
      <% else %>
        <%= link_to "My Posts", user_posts_path(@user), class: "btn btn-outline-primary btn-sm" %>
        <%= link_to "Edit", edit_user_post_path(@user, @post), class: "btn btn-outline-secondary btn-sm" %>

        <hr>
        <%= button_to "Destroy", user_post_path(@user, @post), method: :delete, class: "btn btn-outline-danger btn-sm" %>
      <% end %>
    </div>
  </div>
  <hr>

  <div>
    <%= render partial: "posts/comment", collection: @post.comments %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <tbody>
  <% @decorated_users.each do |decorated_user| %>
    <tr>
      <td><%= link_to decorated_user.full_name, user_path(decorated_user) %></td>
      <td><%= decorated_user.email %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/posts/_form.html.erb
<%= form_with model: post, url: [user, :users, post] do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title, autofocus: true, autocomplete: "title" %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :status %><br />
    <%= form.select :status, Post.status.values %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-outline-secondary btn-sm" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-outline-secondary btn-sm" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name),
              class: "btn btn-outline-secondary btn-sm" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name),
              class: "btn btn-outline-secondary btn-sm" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name),
              class: "btn btn-outline-secondary btn-sm" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}",
                  omniauth_authorize_path(resource_name, provider),
                  data: { turbo: false },
                  class: "btn btn-outline-secondary btn-sm" %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="card weight">
  <div class="card-body">
    <h5 class="card-title">Name</h5>
    <p class="card-text"><%= @user.name %></p>
    <h5 class="card-title">Surname</h5>
    <p class="card-text"><%= @user.surname %></p>
    <h5 class="card-title">Email</h5>
    <p class="card-text"><%= @user.email %></p>

    <div>
        <%= link_to "Posts", user_posts_path(@user), class: "btn btn-outline-primary btn-sm" %>

        <% if current_user == @user %>
          <%= link_to "Edit Account", edit_user_registration_path, class: "btn btn-outline-secondary btn-sm" %>

          <hr>
          <%= button_to "Delete Account", user_path(@user), method: :delete, class: "btn btn-outline-danger btn-sm" %>
        <% end %>
    </div>
  </div>
</div>